spring.application.name=recorever-backend

# Server port (change if 8080 is already used)
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# This path is where images will be physically stored on your VPS.
file.upload-dir=${UPLOAD_DIR}
file.base-url=/api/image/

spring.mvc.async.request-timeout=0